import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import QRCode from 'qrcode';

export const exportToCSV = (data, fileName = 'export.csv') => {
    if (!data.length) return;
    const headers = Object.keys(data[0]);
    const csvRows = [];
    csvRows.push(headers.join(','));
    for (const row of data) {
        const values = headers.map(header => {
            const escaped = ('' + row[header]).replace(/"/g, '\\"');
            return `"${escaped}"`;
        });
        csvRows.push(values.join(','));
    }
    
    const csvContent = csvRows.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    
    if (link.download !== undefined) {
        const url = URL.createObjectURL(blob);
        link.setAttribute('href', url);
        link.setAttribute('download', fileName);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
};

/**
 * Export data to Excel
 */
export const exportToExcel = (data, fileName = 'export', sheetName = 'Data') => {
    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
    XLSX.writeFile(workbook, `${fileName}.xlsx`);
};

/**
 * Export data to PDF with professional layout
 */
export const exportToPDF = (title, columns, data, fileName = 'report', metadata = {}) => {
    const doc = new jsPDF({
        orientation: columns.length > 6 ? 'landscape' : 'portrait',
        unit: 'mm',
        format: 'a4'
    });
    
    const pageWidth = doc.internal.pageSize.width;
    
    // 1. Header Section
    doc.setFillColor(37, 99, 235); // primary-600
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text((metadata.companyName || 'EXPORT LANKA').toUpperCase(), 14, 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Enterprise Resource Management System', 14, 28);
    
    // 2. Report Info (Right-aligned)
    doc.setFontSize(14);
    doc.text(title.toUpperCase(), pageWidth - 14, 20, { align: 'right' });
    
    doc.setFontSize(9);
    doc.text(`Report Date: ${new Date().toLocaleString()}`, pageWidth - 14, 28, { align: 'right' });
    if (metadata.userName) {
        doc.text(`Generated by: ${metadata.userName} (${metadata.userRole || 'User'})`, pageWidth - 14, 34, { align: 'right' });
    }

    // 3. Table Section
    autoTable(doc, {
        startY: 50,
        head: [columns.map(col => col.header)],
        body: data.map(item => columns.map(col => {
            const val = item[col.dataKey];
            if (val === null || val === undefined) return '—';
            if (typeof val === 'number') return val.toLocaleString('en-LK', { minimumFractionDigits: 2 });
            if (typeof val === 'object') return val.name || val.code || JSON.stringify(val);
            return String(val);
        })),
        theme: 'striped',
        headStyles: { 
            fillColor: [30, 41, 59], // slate-800
            textColor: [255, 255, 255],
            fontSize: 9,
            fontStyle: 'bold',
            halign: 'center'
        },
        styles: { 
            fontSize: 8,
            cellPadding: 3,
            valign: 'middle'
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252] // slate-50
        },
        margin: { left: 14, right: 14 },
        didDrawPage: (data) => {
            // Footer
            const str = `Page ${doc.internal.getNumberOfPages()}`;
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(str, pageWidth - 14, doc.internal.pageSize.height - 10, { align: 'right' });
            doc.text('Confidential - System Generated Report', 14, doc.internal.pageSize.height - 10);
        }
    });
    
    doc.save(`${fileName}.pdf`);
};

/**
 * Export a complete Invoice/Quotation document to a high-fidelity PDF locally in browser.
 */
const loadImageBase64 = (url) => {
    return new Promise((resolve) => {
        const img = new Image();
        img.crossOrigin = 'Anonymous';
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.width;
            canvas.height = img.height;
            const ctx = canvas.getContext('2d');
            ctx.drawImage(img, 0, 0);
            resolve(canvas.toDataURL('image/jpeg'));
        };
        img.onerror = () => resolve(null);
        img.src = url;
    });
};

export const exportDocumentToPDF = async (docData, documentType = 'invoice') => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });
    
    const pageWidth = doc.internal.pageSize.width;
    const fmt = (n) => new Intl.NumberFormat('en-LK', { minimumFractionDigits: 2 }).format(n || 0);
    const fmtDate = (d) => d ? new Date(d).toLocaleDateString('en-LK') : '—';
    
    // Draw Elegant Page Border
    doc.setDrawColor(220);
    doc.setLineWidth(0.2);
    doc.rect(5, 5, pageWidth - 10, doc.internal.pageSize.height - 10);
    
    // Load logo
    const logoBase64 = await loadImageBase64('/logo.jpg');
    if (logoBase64) {
        doc.addImage(logoBase64, 'JPEG', 12, 10, 16, 16);
    }
    
    // 1. Header Details (GLS / GLX Grid Layout matching print layout)
    doc.setFont('times', 'bold');
    doc.setFontSize(13);
    doc.text("GLS INDUSTRIES (PVT) LTD", 32, 13);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(80, 80, 80);
    
    // Left Column Address
    const leftText = [
        'No.14, Negambo Road,',
        'Thudella, Ja-Ela,',
        'Sri Lanka.',
        '(11350)'
    ].join('\n');
    doc.text(leftText, 32, 16.5, { lineHeight: 1.3 });
    
    // Center Column Address
    doc.setFont('times', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(0, 0, 0);
    doc.text("GLX TRUCK BODY", 95, 12);
    doc.text("ENGINEERS", 95, 15.5);
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(5);
    doc.setTextColor(100, 100, 100);
    doc.text("ALUMINIUM, STEEL & FREEZER BOX MANUFACTURE", 95, 19.2);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    const centerText = [
        'No.2020/3L, 2, Seeduwa Road,',
        'Kotugoda, Ja-Ela.',
        'Sri Lanka.',
        '(11390)'
    ].join('\n');
    doc.text(centerText, 95, 23, { lineHeight: 1.3 });
    
    // Right Column Contacts
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(0, 0, 0);
    const rightText = [
        'Mobile : 071 6666 888',
        'Tel      : 011 740 4446',
        'Email  : glx.engi@gmail.com',
        'Web    : www.glx.lk'
    ].join('\n');
    doc.text(rightText, 152, 12, { lineHeight: 1.4 });
    
    // Thin divider line
    doc.setDrawColor(200);
    doc.setLineWidth(0.3);
    doc.line(10, 37, pageWidth - 10, 37);
    
    // Determine title
    const isEstimate = docData.documentType === 'estimate' || (docData.quoteNumber && docData.quoteNumber.startsWith('EST'));
    const isInvoice = !!docData.invoiceNumber || docData.documentType === 'invoice';
    let title = 'QUOTATION';
    if (isEstimate) title = 'ESTIMATE';
    if (isInvoice) title = 'INVOICE';
    
    // 3. Metadata Section inside a rounded box
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    
    const docCode = docData.invoiceNumber || docData.quoteNumber || docData.quotationCode || docData._id.toString();
    const docDate = docData.date || docData.invoiceDate || docData.createdAt || Date.now();
    const customerName = docData.customerName || docData.vehicleOwner || docData.customerSnapshot?.name || 'Valued Client';
    const contactPhone = docData.customerPhone || docData.customerSnapshot?.contactName || '';
    
    // Metadata Info Box
    doc.setDrawColor(210);
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(10, 42, pageWidth - 20, 26, 1.5, 1.5, 'FD');
    
    // Left column properties
    doc.setFont('helvetica', 'bold');
    doc.text("Insurance Company:", 14, 47);
    doc.setFont('helvetica', 'normal');
    doc.text(docData.insuranceCompany || 'N/A', 43, 47);
    
    doc.setFont('helvetica', 'bold');
    doc.text("Customer Name:", 14, 52);
    doc.setFont('helvetica', 'normal');
    doc.text(customerName, 39, 52);
    
    doc.setFont('helvetica', 'bold');
    doc.text("Contact Number:", 14, 57);
    doc.setFont('helvetica', 'normal');
    doc.text(contactPhone || 'N/A', 39, 57);
    
    doc.setFont('helvetica', 'bold');
    doc.text("Vehicle No:", 14, 62);
    doc.setFont('helvetica', 'normal');
    doc.text(docData.vehicleNo || 'N/A', 31, 62);
    
    doc.setFont('helvetica', 'bold');
    doc.text("Vehicle Model:", 14, 66);
    doc.setFont('helvetica', 'normal');
    doc.text(docData.vehicleModel || 'N/A', 35, 66);
    
    // Right column properties
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.text(`${title} No : ${docCode}`, 130, 47);
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.text("Sales Rep:", 130, 52);
    doc.setFont('helvetica', 'normal');
    doc.text(docData.salesRep || 'Asanka', 147, 52);
    
    doc.setFont('helvetica', 'bold');
    doc.text("Branch:", 130, 57);
    doc.setFont('helvetica', 'normal');
    doc.text(docData.branch || 'JA-ELA', 142, 57);
    
    doc.setFont('helvetica', 'bold');
    doc.text("Date:", 130, 62);
    doc.setFont('helvetica', 'normal');
    doc.text(fmtDate(docDate), 139, 62);
    
    // 4. Line Items Table
    const tableColumns = ['#', 'DESCRIPTION', 'RATE', 'QTY', 'AMOUNT'];
    const tableRows = (docData.items || [])
        .filter(item => !!item)
        .map((item, idx) => {
            let desc = item.productName || item.description || 'Lorry Body';
            if (item.productTranslation) {
                desc += `\n(${item.productTranslation})`;
            }
            const qty = Number(item.quantity) || 1;
            const price = Number(item.unitPrice) || 0;
            const total = qty * price;
            return [
                idx + 1,
                desc,
                fmt(price),
                qty,
                fmt(total)
            ];
        });
    
    autoTable(doc, {
        startY: 73,
        head: [tableColumns],
        body: tableRows,
        theme: 'grid',
        headStyles: {
            fillColor: [243, 244, 246],
            textColor: [107, 114, 128],
            fontSize: 8,
            fontStyle: 'bold',
            halign: 'left'
        },
        styles: {
            fontSize: 7.5,
            cellPadding: 2.5,
            valign: 'middle',
            lineColor: [229, 231, 235],
            lineWidth: 0.2,
            textColor: [31, 41, 55]
        },
        margin: { left: 10, right: 10 },
        columnStyles: {
            0: { cellWidth: 10, halign: 'center' },
            1: { cellWidth: 100 },
            2: { cellWidth: 35, halign: 'right' },
            3: { cellWidth: 15, halign: 'center' },
            4: { cellWidth: 30, halign: 'right' }
        }
    });
    
    let finalY = doc.lastAutoTable.finalY + 8;
    
    // 5. Totals & Summary Block
    const subtotal = docData.subtotal || docData.totalAmount || (docData.items || []).reduce((sum, item) => sum + (item.quantity * item.unitPrice), 0);
    const discount = (docData.discount || 0) + (docData.specialDiscount || 0);
    const grandTotal = docData.grandTotal || docData.finalSellingPrice || (subtotal - discount);
    
    // Check page space for totals block
    if (finalY > doc.internal.pageSize.height - 75) {
        doc.addPage();
        finalY = 15;
        // Border on page 2
        doc.setDrawColor(220);
        doc.rect(5, 5, pageWidth - 10, doc.internal.pageSize.height - 10);
    }
    
    // Summary Right Box
    doc.setDrawColor(210);
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(pageWidth - 95, finalY, 85, 20, 1.5, 1.5, 'FD');
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(`SUB TOTAL:`, pageWidth - 90, finalY + 6);
    doc.text(`LKR ${fmt(subtotal)}`, pageWidth - 15, finalY + 6, { align: 'right' });
    
    // Thin divider line inside totals box
    doc.setDrawColor(220);
    doc.line(pageWidth - 93, finalY + 10, pageWidth - 12, finalY + 10);
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text(`GRAND TOTAL:`, pageWidth - 90, finalY + 15);
    doc.text(`LKR ${fmt(grandTotal)}`, pageWidth - 15, finalY + 15, { align: 'right' });
    
    // Draw double underlines below Grand Total value
    doc.setDrawColor(0);
    doc.setLineWidth(0.4);
    doc.line(pageWidth - 45, finalY + 16.5, pageWidth - 15, finalY + 16.5);
    doc.line(pageWidth - 45, finalY + 17.5, pageWidth - 15, finalY + 17.5);
    
    // Bank & Warranty Info (Quotations & Estimates)
    if (!isInvoice) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.text('Payment & Bank Details:', 10, finalY + 5);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        const bankDetails = [
            'Account Name: GLX Truck Body Engineers',
            'Bank: Nations Trust Bank, Ja-Ela Branch',
            'Account No: 1001-XXXX-XXXX',
            'Terms: 70% Advance with Order, balance on Completion.'
        ].join('\n');
        doc.text(bankDetails, 10, finalY + 9);
    }
    
    const bottomY = doc.internal.pageSize.height - 40;
    
    // 6. Signatures & QR Code Footer
    // Printed Time
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 100, 100);
    doc.text(`Printed at: ${new Date().toLocaleString('en-GB')}`, 10, bottomY + 8);
    
    // Signature Line
    doc.setDrawColor(0);
    doc.setLineWidth(0.4);
    doc.line(10, bottomY + 22, 75, bottomY + 22);
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(0, 0, 0);
    doc.text('GLX INDUSTRIES - JA ELA', 10, bottomY + 26);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.text('Authorized Signature', 10, bottomY + 29.5);
    
    // QR Code Box (Right Side)
    doc.setDrawColor(210);
    doc.setLineWidth(0.2);
    doc.roundedRect(pageWidth - 38, bottomY, 28, 33, 1, 1, 'D');
    
    // Generate QR
    const qrDataObj = {
        type: title,
        number: docCode,
        date: fmtDate(docDate),
        customer: customerName,
        vehicleNo: docData.vehicleNo || 'N/A',
        grandTotal: grandTotal,
        status: docData.status || 'Active'
    };
    try {
        const qrBase64 = await QRCode.toDataURL(JSON.stringify(qrDataObj));
        doc.addImage(qrBase64, 'PNG', pageWidth - 34, bottomY + 2, 20, 20);
        
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(6);
        doc.setTextColor(50, 50, 50);
        doc.text('SCAN TO VERIFY', pageWidth - 24, bottomY + 25.5, { align: 'center' });
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(5.5);
        doc.text(docCode, pageWidth - 24, bottomY + 29, { align: 'center' });
    } catch (e) {
        console.warn('Failed to render QR on PDF', e);
    }
    
    doc.save(`${title.toLowerCase()}_${docCode.replace(/[\\/:*?"<>|]/g, '_')}.pdf`);
};
